name: CI - Build & Push Strapi Image

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate unique image tag
        id: tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          DATE_TAG=$(date +%Y%m%d-%H%M%S)
          IMAGE_TAG="$SHORT_SHA-$DATE_TAG"
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          ECR_REPO: ${{ secrets.ECR_REPO }}
        run: docker build -t strapi-app:$IMAGE_TAG .

      - name: Tag Docker image for ECR
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          ECR_REPO: ${{ secrets.ECR_REPO }}
        run: docker tag strapi-app:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG

      - name: Push Docker image to ECR
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          ECR_REPO: ${{ secrets.ECR_REPO }}
        run: docker push $ECR_REPO:$IMAGE_TAG

      - name: Tag as latest
        env:
          ECR_REPO: ${{ secrets.ECR_REPO }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest
          docker push $ECR_REPO:latest
